apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-db
  name: db
spec:
  ports:
    - name: "5432"
      port: {{ .Values.service.port }}
      targetPort: 5432
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-db
status:
  loadBalancer: {}
