{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-{{ .Chart.Name }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
# This config is for solving the bug when use /run/secrets as a mount point
# https://github.com/kubernetes/kubernetes/issues/65835
automountServiceAccountToken: false
{{- end }}
