apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-config
  name: {{ .Release.Name }}-config
data:
  DATABASE: postgres
  DEBUG: "0"
  DEVELOPMENT: "0"
  SANDBOX: "0"
  REDIS_HOST: redis://redis:6379/1
  ADMIN_EPPNS: {{ .Values.app.admin.admin_eppns }}
  SQL_ENGINE: django.db.backends.postgresql
  {{- with .Values.global.django }}
  SECRET_KEY_FILE: {{ .secret_key_file | quote }}
  SQL_HOST: {{ .postgres_host | default "db" | quote }}
  SQL_PORT: {{ .postgres_port | default "5432" | quote }}
  POSTGRES_DB: {{ .postgres_db | quote }}
  POSTGRES_USER: {{ .postgres_user | quote}}
  POSTGRES_PASSWORD_FILE: {{ .postgres_password_file | quote }}
  {{- end }}
  {{- with .Values.websp.shib }}
  DJANGO_ALLOWED_HOSTS: "localhost 127.0.0.1 [::1] app {{ .map_host_name }}"
  MAP_HOST_NAME: {{ .map_host_name }}
  IDP_HOST_NAME: {{ .idp_host_name | default "" }}
  METADATA_PROVIDERS: {{ .metadata_providers | quote }}
  IDP_SSO: {{ .idp_sso | quote }}
  {{- end }}
  {{- if eq .Values.websp.service.type "NodePort" }}
  MAP_HOST_PORT: {{ .Values.websp.service.nodePort | default "443"  | quote }}
  {{- end }}
  {{- if eq .Values.websp.service.type "ClusterIP" }}
  MAP_HOST_PORT: "443"
  {{- end }}