apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: app
  name: app
spec:
  ports:
    - name: "8080"
      port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app.kubernetes.io/name: app
status:
  loadBalancer: {}
